### PR TITLE
feat(nsg): create network security group

### LINKED ISSUE #24: feat(nsg): create network security group
Create a submodule `nsg` to create a network security group.

[Relevant Terraform resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/network_security_group).

### PR DESCRIPTION
**Pull request by hknutsen**
Add submodule for creating a network security group (NSG).

Fixes #24

### CODE REVIEW

**Comment by hknutsen** [comment]
Tests pass, however I'm considering using the `security_rules` block instead of the argument. Reason being that making changes to a security rule currently requires changing the entire security rule. Using the block instead might make fine-grained changes easier.

**Comment by hknutsen** [comment]
Using the block instead did not make a difference.

**Comment by hknutsen** [comment]
Tests pass 🎉

**Review by sebastianlolv — APPROVED** [review]
LGTM + Tests pass 🥇

**Pull request merged**
