### PR TITLE
feat: set diagnostic setting enabled log categories

### PR DESCRIPTION
**Pull request by kov117**
test passed 👍🏽

### CODE REVIEW

**Comment by hknutsen** [comment]
Is this something that should be enabled by default? Is `VMProtectionAlerts` required for audit logging?

**Comment by kov117** [comment]
so far in my research it does not appear to be required for audit logging, infact it may not be actually functional based on my research. 

Ref.
https://github.com/MicrosoftDocs/azure-docs/issues/55372#issuecomment-901547818

**Comment by hknutsen** [comment]
If it's not needed, and it doesn't even work, I'd remove it.

**Comment by helenakallekleiv** [comment]
As far as I could tell it's not needed for audit logging.

**Comment by kov117** [comment]
Removed the entirety of diagnostic settings and log categories as there was no need for them. As previously discussed the categori ``VMProtectionAlerts`` is not required for audit logging. and as my research has shown before, there is no other categori that can be used for audit logging. Therefore it was decided that diagnostic setting and log categories is no longer needed for this module.

**Pull request closed without merging**
